services:
  proxy:
    image: nginx:alpine
    container_name: dnd_proxy
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
      - phpmyadmin
    networks:
      - dnd_net

  app:
    build:
      context: ./src
      dockerfile: ../docker/Dockerfile
    container_name: dnd_app
    volumes:
      - ./src:/var/www/html
    ports:
      - "5173:5173"
    expose:
      - "80"
    depends_on:
      - db
    networks:
      - dnd_net
      
  db:
    image: mysql:8.0
    container_name: dnd_db
    restart: always
    environment:
      MYSQL_DATABASE: dnd
      MYSQL_USER: dnduser
      MYSQL_PASSWORD: dndpass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dnd_dbdata:/var/lib/mysql
    ports:
    - "3307:3306"
    networks:
      - dnd_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dnd_phpmyadmin
    environment:
      PMA_HOST: db
    expose:
      - "80"
    depends_on:
      - db
    networks:
      - dnd_net

volumes:
  dnd_dbdata:

networks:
  dnd_net:
    driver: bridge
