services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: dnd_app
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:80"
      - "5173:5173"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: dnd_db
    restart: always
    environment:
      MYSQL_DATABASE: dnd
      MYSQL_USER: dnduser
      MYSQL_PASSWORD: dndpass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dnd_dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dnd_phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  dnd_dbdata:
