services:
  proxy:
    image: nginx:alpine
    container_name: dnd_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - dnd_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dnd_frontend
    restart: always
    expose:
      - "80"
    volumes:
      - ./frontend/public:/usr/share/nginx/html:ro
    networks:
      - dnd_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dnd_backend
    restart: always
    expose:
      - "80"
    depends_on:
      - db
    volumes:
      - ./backend:/var/www/html
    networks:
      - dnd_net

  db:
    image: mysql:8.0
    container_name: dnd_db
    restart: always
    environment:
      MYSQL_DATABASE: dnd
      MYSQL_USER: dnduser
      MYSQL_PASSWORD: dndpass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /Dragons/docker/db:/var/lib/mysql
      - /Dragons/backups/db:/backups

    ports:
      - "3307:3306"
    networks:
      - dnd_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dnd_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
    expose:
      - "80"
    depends_on:
      - db
    networks:
      - dnd_net

volumes:
  dnd_dbdata:
  backend_vendor:
  backend_node:
  backend_build:

networks:
  dnd_net:
    driver: bridge
