version: "3.9"

services:
  proxy:
    image: nginx:alpine
    container_name: dnd_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - dnd_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dnd_frontend
    restart: always
    expose:
      - "80"
    networks:
      - dnd_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dnd_backend
    restart: always
    expose:
      - "80"
    depends_on:
      - db
    networks:
      - dnd_net
    volumes:
      - ./backend/.env:/var/www/html/.env
      # No montes storage ni bootstrap/cache desde host, que Laravel se encargue dentro del contenedor


  db:
    image: mysql:8.0
    container_name: dnd_db
    restart: always
    environment:
      MYSQL_DATABASE: dnd
      MYSQL_USER: dnduser
      MYSQL_PASSWORD: dndpass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - dnd_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dnd_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - dnd_net

networks:
  dnd_net:
    driver: bridge

volumes:
  db_data:
